baseurl = "https://ariadnavigo.xyz/"
title = "Ariadna's Blog"
languageCode = "en-us"
# Add it only if you keep the theme in the `themes` directory.
# Remove it if you use the theme as a remote Hugo Module.
theme = "re-terminal"
pagination.pagerSize = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink", "paper"]
  themeColor = "pink"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


  # you can set a banner on the top of the page with a call to action
  # defaults: dismissible = false; URL is optional
  # [params.banner]
  # dismissible = false
  # text = "Check it out on GitHub"
  # url = "https://github.com/mirus-ua/hugo-theme-re-terminal"

  # Hide comments by default
  hideComments = true

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Ariadna's Blog"
    subtitle = "A Blog about FOSS, Coding, Life, and Other Assorted Things"
    owner = "Ariadna Vigo"
    keywords = "blog, programming, personal"
    copyright = "Copyright &copy; Ariadna Vigo"
    menuMore = "Show More"
    readMore = "Read More"
    readOtherPosts = "Read Other Posts"
    newerPosts = "Newer Posts"
    olderPosts = "Older Posts"
    missingContentMessage = "Page Not Found..."
    missingBackButtonLabel = "Back To Home Page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Ariadna's Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      # Submenus is available since v2.1.0
      # [[languages.en.menu.main]]
      #   identifier = "submenuParent"
      #   name = "Submenu"
      # [[languages.en.menu.main]]
      #   parent = "submenuParent"
      #   identifier = "anItem"
      #   name = "AnItem"

      [[languages.en.menu.main]]
      	identifier = "tags"
	name = "Tags"
	url = "/tags"
	weight = 1

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
	weight = 2

#[module]
  # In case you would like to make changes to the theme and keep it locally in you repository,
  # uncomment the line below (and correct the local path if necessary).
  # --
  # replacements = "github.com/mirus-ua/hugo-theme-re-terminal -> themes/re-terminal"
#[[module.imports]]
  #path = 'github.com/mirus-ua/hugo-theme-re-terminal'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
    keepQuotes = true # Fixing metadata that reqires quotes

[markup]
  [markup.goldmark.extensions]
  linkify = false # deactivating autolinks
